import { Header } from "@/components";
import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <QueryProvider>
          <Header streamerId="chzzk" streamerImg="https://avatars.githubusercontent.com/u/123456789?v=4" />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
